spring.application.name=app

# Nivel de logs por paquete
logging.level.com.doumo.app=DEBUG
logging.level.com.doumo.app.service=DEBUG
logging.level.com.doumo.app.controller=INFO

# Guardar en archivo
logging.file.name=logs/app.log
logging.file.path=./logs

# Formato
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n